# Generated by Django 4.2.3 on 2024-02-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghg_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refrigerant',
            name='emission',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
    ]
