# Generated by Django 4.2.3 on 2024-02-17 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghg_inventory', '0002_refrigerant_emission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refrigerant_ef',
            old_name='GWP',
            new_name='emission_factor',
        ),
    ]
