# Generated by Django 4.2.3 on 2024-02-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghg_inventory', '0003_rename_gwp_refrigerant_ef_emission_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refrigerant',
            name='emission',
            field=models.FloatField(),
        ),
    ]
