# Generated by Django 4.2.3 on 2024-02-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghg_inventory', '0004_alter_refrigerant_emission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electricity_EF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emission_factor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='electricity',
            name='emission',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
    ]
