# Generated by Django 4.2.3 on 2024-02-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghg_inventory', '0005_electricity_ef_electricity_emission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricity_ef',
            name='emission_factor',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='refrigerant_ef',
            name='emission_factor',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
