# Generated by Django 4.2.3 on 2024-02-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghg_inventory', '0006_alter_electricity_ef_emission_factor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commute',
            name='emission',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
