# Generated by Django 4.2.3 on 2024-02-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghg_inventory', '0008_water_emission'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastewater',
            name='emission',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
