# Generated by Django 4.2.3 on 2024-02-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghg_inventory', '0009_wastewater_emission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material_EF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('emission_factor', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='emission',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
