# Generated by Django 4.2.3 on 2024-02-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghg_inventory', '0010_material_ef_material_emission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.CharField(choices=[('Land line', 'Land line'), ('Tablet', 'Tablet'), ('Phone (Multifunction Device)', 'Phone (Multifunction Device)'), ('Camera Battery', 'Camera Battery'), ('Office Paper', 'Office Paper'), ('Toilet Paper', 'Toilet Paper'), ('Mixed Can', 'Mixed Can'), ('Office Chair', 'Office Chair'), ('Wooden Table', 'Wooden Table'), ('Bean Bag Chair', 'Bean Bag Chair'), ('Monitor - Desktop', 'Monitor - Desktop'), ('Office Desk', 'Office Desk'), ('Bottled Water (m3)', 'Bottled Water (m3)')], max_length=30),
        ),
    ]
