# Generated by Django 4.2.3 on 2024-02-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghg_inventory', '0011_alter_material_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disposal_EF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40)),
                ('emission_factor', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
    ]
