# Generated by Django 4.2.3 on 2024-02-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghg_inventory', '0012_disposal_ef'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposal',
            name='emission',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
