# Generated by Django 4.2.3 on 2024-02-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghg_inventory', '0016_flight_ef_flight_emission'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='emission',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
